"""
Visualize nominal trajectory generated by SCvx.

This script:
1. Loads saved nominal trajectory
2. Creates comprehensive visualizations:
   - 2D workspace with obstacles and trajectory
   - State trajectories vs time
   - Input trajectories vs time
   - SCvx convergence plots
   - Clearance plot

Usage:
    python scripts/01b_visualize_nominal.py [trajectory_file]

    If no file is specified, loads the most recent trajectory.
"""

import pickle
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from ddfs.environment.collision import CollisionChecker  # noqa: E402
from ddfs.environment.obstacles import CircularObstacle, EllipsoidalObstacle  # noqa: E402
from ddfs.environment.workspace import Workspace  # noqa: E402


def load_trajectory(filepath=None):
    """
    Load trajectory from file.

    Args:
        filepath: Path to trajectory file (optional)

    Returns:
        data: Trajectory data dictionary
        folder_path: Path to trajectory folder
    """
    if filepath is None:
        # Find most recent trajectory folder
        traj_dir = Path("data/nominal_trajectories")
        if not traj_dir.exists():
            raise FileNotFoundError(f"Trajectory directory not found: {traj_dir}")

        # Get all trajectory folders
        folders = [f for f in traj_dir.iterdir() if f.is_dir() and f.name.startswith("unicycle_nominal_")]

        if len(folders) == 0:
            raise FileNotFoundError(f"No trajectory folders found in {traj_dir}")

        # Sort by modification time, get most recent
        folder_path = max(folders, key=lambda p: p.stat().st_mtime)

        # Find pickle file in folder
        pkl_files = list(folder_path.glob("*.pkl"))
        if len(pkl_files) == 0:
            raise FileNotFoundError(f"No .pkl file found in {folder_path}")

        filepath = pkl_files[0]
        print(f"📂 Loading most recent trajectory: {folder_path.name}/")
        print(f"   File: {filepath.name}")
    else:
        filepath = Path(filepath)
        if not filepath.exists():
            raise FileNotFoundError(f"Trajectory file not found: {filepath}")

        folder_path = filepath.parent
        print(f"📂 Loading trajectory: {folder_path.name}/")
        print(f"   File: {filepath.name}")

    with open(filepath, "rb") as f:
        data = pickle.load(f)

    return data, folder_path


def create_obstacles_from_data(obstacle_configs):
    """Create obstacle objects from saved config."""
    obstacles = []

    for obs_config in obstacle_configs:
        obs_type = obs_config["type"]

        if obs_type == "circle":
            obs = CircularObstacle(
                center=np.array(obs_config["center"]),
                radius=obs_config["radius"],
                safety_margin=obs_config.get("safety_margin", 0.0),
            )
            obstacles.append(obs)

        elif obs_type == "ellipse":
            obs = EllipsoidalObstacle(
                center=np.array(obs_config["center"]),
                semi_axes=np.array(obs_config["semi_axes"]),
                rotation=obs_config.get("rotation", 0.0),
                safety_margin=obs_config.get("safety_margin", 0.0),
            )
            obstacles.append(obs)

    return obstacles


def plot_workspace_trajectory(ax, data, obstacles, collision_checker):
    """
    Plot 2D workspace with trajectory.

    Args:
        ax: Matplotlib axes
        data: Trajectory data
        obstacles: List of obstacles
        collision_checker: CollisionChecker
    """
    x_traj = data["x_traj"]
    x0 = data["x0"]
    xf = data["xf"]
    ws_bounds = data["workspace_bounds"]

    # Create workspace
    workspace = Workspace(bounds=ws_bounds, obstacles=obstacles)
    workspace.visualize(ax=ax, show_grid=True, title="SCvx Nominal Trajectory")

    # Plot trajectory with heading arrows
    workspace.plot_trajectory_with_heading(
        x_traj,
        ax=ax,
        color="blue",
        linewidth=2.5,
        arrow_spacing=5,
        arrow_length=0.3,
        label="Nominal Trajectory",
        show_start_goal=False,
    )

    # Mark start and goal
    ax.plot(x0[0], x0[1], "go", markersize=15, label="Start", zorder=10, markeredgecolor="darkgreen", markeredgewidth=2)
    ax.plot(xf[0], xf[1], "r*", markersize=20, label="Goal", zorder=10, markeredgecolor="darkred", markeredgewidth=1.5)

    # Check for collisions and mark them
    collision, timestep, obs_idx = collision_checker.check_trajectory_collision(x_traj)
    if collision:
        collision_point = x_traj[timestep, :2]
        ax.plot(
            collision_point[0],
            collision_point[1],
            "rx",
            markersize=20,
            markeredgewidth=3,
            label=f"Collision (t={timestep})",
            zorder=11,
        )

    ax.legend(loc="upper left", fontsize=10)
    ax.set_aspect("equal", adjustable="box")


def plot_state_trajectories(axes, data):
    """
    Plot state trajectories vs time.

    Args:
        axes: List of 3 matplotlib axes [ax_x, ax_y, ax_theta]
        data: Trajectory data
    """
    x_traj = data["x_traj"]
    dt = data["dt"]
    N = data["N"]
    x_bounds = data["x_bounds"]
    x_min, x_max = x_bounds

    time = np.arange(N + 1) * dt

    state_names = ["x position", "y position", "heading θ"]
    state_units = ["m", "m", "rad"]

    for i, (ax, name, unit) in enumerate(zip(axes, state_names, state_units)):
        # Plot trajectory
        ax.plot(time, x_traj[:, i], "b-", linewidth=2, label="Trajectory")

        # Plot bounds
        ax.axhline(x_min[i], color="r", linestyle="--", linewidth=1.5, alpha=0.7, label="Bounds")
        ax.axhline(x_max[i], color="r", linestyle="--", linewidth=1.5, alpha=0.7)

        # Mark start and goal
        ax.plot(0, x_traj[0, i], "go", markersize=8, zorder=10)
        ax.plot(time[-1], x_traj[-1, i], "r*", markersize=12, zorder=10)

        ax.set_xlabel("Time [s]", fontsize=10)
        ax.set_ylabel(f"{name} [{unit}]", fontsize=10)
        ax.grid(True, alpha=0.3)
        ax.legend(loc="best", fontsize=8)

        # Set title
        if i == 0:
            ax.set_title("State Trajectories vs Time", fontsize=12, fontweight="bold")


def plot_input_trajectories(axes, data):
    """
    Plot input trajectories vs time.

    Args:
        axes: List of 2 matplotlib axes [ax_v, ax_omega]
        data: Trajectory data
    """
    u_traj = data["u_traj"]
    dt = data["dt"]
    N = data["N"]
    u_bounds = data["u_bounds"]
    u_min, u_max = u_bounds

    time = np.arange(N) * dt

    input_names = ["Linear velocity v", "Angular velocity ω"]
    input_units = ["m/s", "rad/s"]

    for i, (ax, name, unit) in enumerate(zip(axes, input_names, input_units)):
        # Plot trajectory
        ax.plot(time, u_traj[:, i], "b-", linewidth=2, label="Input")

        # Plot bounds
        ax.axhline(u_min[i], color="r", linestyle="--", linewidth=1.5, alpha=0.7, label="Bounds")
        ax.axhline(u_max[i], color="r", linestyle="--", linewidth=1.5, alpha=0.7)

        ax.set_xlabel("Time [s]", fontsize=10)
        ax.set_ylabel(f"{name} [{unit}]", fontsize=10)
        ax.grid(True, alpha=0.3)
        ax.legend(loc="best", fontsize=8)

        # Set title
        if i == 0:
            ax.set_title("Input Trajectories vs Time", fontsize=12, fontweight="bold")


def plot_convergence(axes, data):
    """
    Plot SCvx convergence history.

    Args:
        axes: List of 2 matplotlib axes [ax_cost, ax_rho]
        data: Trajectory data
    """
    if "metadata" not in data or "scvx_history" not in data["metadata"]:
        # No history available
        for ax in axes:
            ax.text(
                0.5, 0.5, "No convergence data available", ha="center", va="center", transform=ax.transAxes, fontsize=12
            )
            ax.set_xticks([])
            ax.set_yticks([])
        return

    history = data["metadata"]["scvx_history"]
    cost = history["cost"]
    rho = history["trust_region_rho"]

    if len(cost) == 0:
        for ax in axes:
            ax.text(0.5, 0.5, "SCvx did not converge", ha="center", va="center", transform=ax.transAxes, fontsize=12)
            ax.set_xticks([])
            ax.set_yticks([])
        return

    iterations = np.arange(len(cost))

    # Plot cost
    ax_cost = axes[0]
    ax_cost.plot(iterations, cost, "b-o", linewidth=2, markersize=6)
    ax_cost.set_xlabel("Iteration", fontsize=10)
    ax_cost.set_ylabel("Cost", fontsize=10)
    ax_cost.set_title("SCvx Cost Convergence", fontsize=12, fontweight="bold")
    ax_cost.grid(True, alpha=0.3)

    # Add cost reduction annotation
    if len(cost) > 1:
        cost_reduction = cost[0] - cost[-1]
        ax_cost.text(
            0.98,
            0.98,
            f"Reduction: {cost_reduction:.2f}",
            transform=ax_cost.transAxes,
            ha="right",
            va="top",
            bbox={"boxstyle": "round", "facecolor": "wheat", "alpha": 0.5},
            fontsize=9,
        )

    # Plot trust region radius
    ax_rho = axes[1]
    ax_rho.plot(iterations, rho, "r-s", linewidth=2, markersize=6)
    ax_rho.set_xlabel("Iteration", fontsize=10)
    ax_rho.set_ylabel("Trust Region Radius ρ", fontsize=10)  # noqa: RUF001
    ax_rho.set_title("Trust Region Evolution", fontsize=12, fontweight="bold")
    ax_rho.grid(True, alpha=0.3)
    ax_rho.set_yscale("log")


def plot_clearance(ax, data, collision_checker):
    """
    Plot obstacle clearance along trajectory.

    Args:
        ax: Matplotlib axes
        data: Trajectory data
        collision_checker: CollisionChecker
    """
    x_traj = data["x_traj"]
    dt = data["dt"]
    N = data["N"]

    time = np.arange(N + 1) * dt

    # Compute clearance at each timestep
    clearances = []
    for k in range(N + 1):
        dist, _ = collision_checker.distance_to_nearest_obstacle(x_traj[k])
        clearances.append(dist)

    clearances = np.array(clearances)

    # Plot clearance
    ax.plot(time, clearances, "b-", linewidth=2, label="Clearance")
    ax.axhline(0, color="r", linestyle="-", linewidth=2, label="Collision boundary")

    # Shade collision region
    ax.fill_between(time, -1, 0, color="red", alpha=0.2, label="Collision zone")

    # Mark minimum clearance
    min_clearance = np.min(clearances)
    min_idx = np.argmin(clearances)
    ax.plot(
        time[min_idx],
        min_clearance,
        "ro",
        markersize=10,
        zorder=10,
        label=f"Min: {min_clearance:.3f}m @ t={time[min_idx]:.1f}s",
    )

    ax.set_xlabel("Time [s]", fontsize=10)
    ax.set_ylabel("Distance to Nearest Obstacle [m]", fontsize=10)
    ax.set_title("Obstacle Clearance vs Time", fontsize=12, fontweight="bold")
    ax.grid(True, alpha=0.3)
    ax.legend(loc="best", fontsize=9)

    # Set y-limits to show context
    y_min = min(-0.5, np.min(clearances) - 0.2)
    y_max = max(1.0, np.max(clearances) + 0.2)
    ax.set_ylim(y_min, y_max)


def create_visualization(data):
    """
    Create comprehensive visualization of trajectory.

    Args:
        data: Trajectory data
    """
    # Create obstacles
    obstacles = create_obstacles_from_data(data["obstacles"])
    collision_checker = CollisionChecker(obstacles)

    # Create figure with subplots
    fig = plt.figure(figsize=(18, 12))
    gs = fig.add_gridspec(3, 3, hspace=0.3, wspace=0.3)

    # 1. Workspace plot (large, top-left)
    ax_workspace = fig.add_subplot(gs[0:2, 0:2])
    plot_workspace_trajectory(ax_workspace, data, obstacles, collision_checker)

    # 2. State trajectories (right column, top)
    ax_state_x = fig.add_subplot(gs[0, 2])
    ax_state_y = fig.add_subplot(gs[1, 2])
    ax_state_theta = fig.add_subplot(gs[2, 2])
    plot_state_trajectories([ax_state_x, ax_state_y, ax_state_theta], data)

    # 3. Input trajectories (bottom-left)
    ax_input_v = fig.add_subplot(gs[2, 0])
    ax_input_omega = fig.add_subplot(gs[2, 1])
    plot_input_trajectories([ax_input_v, ax_input_omega], data)

    # 4. Convergence plots (middle row, left)
    # Adjust to make room for clearance plot
    fig2 = plt.figure(figsize=(14, 5))
    gs2 = fig2.add_gridspec(1, 3, hspace=0.3, wspace=0.3)

    ax_cost = fig2.add_subplot(gs2[0, 0])
    ax_rho = fig2.add_subplot(gs2[0, 1])
    plot_convergence([ax_cost, ax_rho], data)

    # 5. Clearance plot
    ax_clearance = fig2.add_subplot(gs2[0, 2])
    plot_clearance(ax_clearance, data, collision_checker)

    # Add super title to main figure
    metadata = data.get("metadata", {})
    converged = metadata.get("converged", False)
    iterations = metadata.get("iterations", 0)

    status = "CONVERGED" if converged else "MAX ITERATIONS"
    fig.suptitle(
        f"SCvx Nominal Trajectory - {status} (Iterations: {iterations})", fontsize=16, fontweight="bold", y=0.995
    )

    return fig, fig2


def print_summary(data):
    """Print trajectory summary."""
    print("\n" + "=" * 70)
    print("TRAJECTORY SUMMARY")
    print("=" * 70)

    x_traj = data["x_traj"]
    u_traj = data["u_traj"]
    metadata = data.get("metadata", {})

    print("\n Planning:")
    print(f"   Initial state:   {data['x0']}")
    print(f"   Goal state:      {data['xf']}")
    print(f"   Horizon:         {data['N']} steps ({data['N'] * data['dt']:.1f}s)")

    print("\n Convergence:")
    converged = metadata.get("converged", False)
    iterations = metadata.get("iterations", 0)
    print(f"   Status:          {'Converged' if converged else 'Max iterations'}")
    print(f"   Iterations:      {iterations}")

    if "validation" in metadata:
        val = metadata["validation"]
        print("\n Validation:")
        print(f"   Collision-free:  {'Collision-free' if not val['collision']['detected'] else 'Collision detected'}")
        print(f"   Min clearance:   {val['clearance']['minimum']:.4f} m")
        print(f"   Goal error:      {val['goal_error']:.6f} m")
        print(f"   Max lin error:   {val['linearization']['max_error']:.6f}")

    # Trajectory statistics
    distances = np.linalg.norm(np.diff(x_traj[:, :2], axis=0), axis=1)
    total_distance = np.sum(distances)

    print("\n Trajectory:")
    print(f"   Distance:        {total_distance:.3f} m")
    print(f"   Avg velocity:    {np.mean(u_traj[:, 0]):.3f} m/s")
    print(f"   Max velocity:    {np.max(u_traj[:, 0]):.3f} m/s")
    print(f"   Avg |ω|:         {np.mean(np.abs(u_traj[:, 1])):.3f} rad/s")

    print("=" * 70 + "\n")


def save_plots(fig1, fig2, folder_path):
    """
    Save plot figures to folder.

    Args:
        fig1: Main figure
        fig2: Convergence figure
        folder_path: Path to trajectory folder
    """
    # Save main figure
    main_plot_path = folder_path / "trajectory_visualization.png"
    fig1.savefig(main_plot_path, dpi=150, bbox_inches="tight")
    print(f"    Saved: {main_plot_path.name}")

    # Save convergence figure
    convergence_plot_path = folder_path / "convergence_analysis.png"
    fig2.savefig(convergence_plot_path, dpi=150, bbox_inches="tight")
    print(f"    Saved: {convergence_plot_path.name}")

    # Also save as PDF for high quality
    main_plot_pdf = folder_path / "trajectory_visualization.pdf"
    fig1.savefig(main_plot_pdf, bbox_inches="tight")
    print(f"    Saved: {main_plot_pdf.name}")

    convergence_plot_pdf = folder_path / "convergence_analysis.pdf"
    fig2.savefig(convergence_plot_pdf, bbox_inches="tight")
    print(f"    Saved: {convergence_plot_pdf.name}")


def main():
    """Main execution function."""
    print("NOMINAL TRAJECTORY VISUALIZATION")

    # Load trajectory
    filepath = sys.argv[1] if len(sys.argv) > 1 else None

    try:
        data, folder_path = load_trajectory(filepath)
    except Exception as e:
        print(f"❌ Error loading trajectory: {e}")
        return 1

    # Print summary
    print_summary(data)

    # Create visualizations
    print("🎨 Creating visualizations...")

    try:
        fig1, fig2 = create_visualization(data)
        print("✓ Visualizations created")
    except Exception as e:
        print(f"❌ Error creating visualizations: {e}")
        import traceback  # noqa: PLC0415

        traceback.print_exc()
        return 1

    # Save plots
    print(f"\n💾 Saving plots to: {folder_path}/")
    try:
        save_plots(fig1, fig2, folder_path)
        print("✓ All plots saved")
    except Exception as e:
        print(f"❌ Error saving plots: {e}")
        import traceback  # noqa: PLC0415

        traceback.print_exc()
        return 1

    print("VISUALIZATION COMPLETE")


    print(f"📁 All files saved in: {folder_path}/")
    print("   • Trajectory data (.pkl)")
    print("   • Visualization plots (.png, .pdf)")

    return 0


if __name__ == "__main__":
    exit_code = main()
    sys.exit(exit_code)
